from django.shortcuts import render
from app.forms import CreatePokemonForm, TypeForm
from app.models import Created_mon, create_mon


def create(request):
    if request.GET:
        form = CreatePokemonForm(request.GET)
        if form.is_valid():
            creator = form.cleaned_data['creator']
            name = form.cleaned_data['name']
            height = form.cleaned_data['height']
            weight = form.cleaned_data['weight']
            region = form.cleaned_data['region']
            description = form.cleaned_data['description']
            type1 = form.cleaned_data['type1']       
            type2 = form.cleaned_data['type2']
            creation = create_mon(creator, name, height, weight, region, description, type1, type2)
            return render(request, "create.html", {"form": form, "creation": creation})
    else:
        form=CreatePokemonForm()
    return render(request, "create.html", {"form":form})


def entry(request, pokemon):
    context = {
        "pokemon": pokemon,
        "Pokemon": Pokemon,
    }
    return render(request, "entry.html", context)
        

def user_entry(request, pokemon):
    context = {
        "pokemon": pokemon,
        "Created_mon": Created_mon.objects.all()
    }
    return render(request, "user_entry.html", context)

def dex(request):
    if request.GET:
        form = TypeForm(request.GET)
        if form.is_valid():
             poketype = form.cleaned_data["poketype"].title()
             type_list = []
             for mon, data in Pokemon.items():
                 if data.type1 == poketype or data.type2 == poketype:
                    type_list.append(mon)
             context = {
                 "Pokemon_links": Pokemon_links,
                 "type_list": type_list,
                 "filter": True,
                 "form": form,
                 "Created_mon": Created_mon.objects.all()
                 }
    else:
        form = TypeForm()
        context = {
            "form": form,
            "Pokemon_links": Pokemon_links,
            "filter": False,
            "Created_mon": Created_mon.objects.all()
            }
    return render(request, "dex.html", context)

            
class Gen_1:    
    def __init__(self, name, height, weight, region, description, type1, type2):
        self.name = name
        self.height = height
        self.weight = weight
        self.region = region
        self.description = description
        self.type1 = type1
        self.type2 = type2



Pokemon = {
    "Bulbasaur": Gen_1("Bulbasaur", 0.7, 6.9, "Kanto", "Bulbasaur can be seen napping in bright sunlight.  There is a seed on its back.  By soaking up the sun's rays, the seed grows progressively larger.", "Grass", "Poison"),
    "Ivysaur": Gen_1("Ivysaur", 1.0, 13.0, "Kanto", "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.", "Grass", "Poison"),
    "Venusaur": Gen_1("Venusaur", 2.0, 100.0, "Kanto", "Its plant blooms when it is absorbing solar energy.  It stays on the move to seek sunlight.", "Grass", "Poison"),
    "Charmander": Gen_1("Charmander", 0.6, 8.5, "Kanto", "The flame that burns at the tip of its tail is an indication of its emotions.  The flame wavers when Charmander is enjoying itself.  If the pokémon becomes enraged the flame burns fiercely.", "Fire", None),
    "Charmeleon": Gen_1("Charmeleon", 1.1, 19.0, "Kanto", "Charmeleon mercilessly destroys its foes using its sharp claws.  If it encounters a strong foe, it turns aggressive.  In this excited state, the flame at the tip of its tail flares with a bluish white color.", "Fire", None),
    "Charizard": Gen_1("Charizard", 1.7, 90.5, "Kanto", "It spits fire that is hot enough to melt boulders.  It may cause forest fires by blowing flames.", "Fire", "Flying"),
    "Squirtle": Gen_1("Squirtle", 0.5, 9.0, "Kanto", "Squirtle's shell is not meerely used for protection.  The shell's rounded shape and the grooves on its surface help minimize resistance in water, enabling this pokémon to swim at high speeds.", "Water", None),
    "Wartortle": Gen_1("Wartortle", 1.0, 22.5, "Kanto","It is recognized as a symbol of lengevity.  If its shell has algae on it, that Wartortle is very old.", "Water", None),
    "Blastoise": Gen_1("Blastoise", 1.6, 85.5, "Kanto","It crushes its foe under its heavy body to cause fainting.  In a pinch, it will withdraw inside its shell", "Water", None),
    "Caterpie": Gen_1("Caterpie", 0.3, 2.9, "Kanto", "For protection, it releases a horribly stench from the antenna on its head to drive away enemies.","Bug", None),
    "Metapod": Gen_1("Metapod", 0.7, 9.9, "Kanto", "It is waiting for the moment to evolve.  At this stage, it can only harden, so it remains motionless to avoid attack.", "Bug", None),
    "Butterfree": Gen_1("Butterfree", 1.1, 32.0, "Kanto", "In battle, it flaps its wings at great speed to release highly toxic dust into the air.", "Bug", "Flying"),
    "Weedle": Gen_1("Weedle", 0.3, 3.2, "Kanto", "Beware of the sharp stinger on its head.  It hides in grass and bushes where it eats leaves.", "Bug", "Poison"),
    "Kakuna": Gen_1("Kakuna",  0.6, 10.0, "Kanto", "Able to move on ly slightly.  When endangered, it may stick out its stinger and poison its enemy.", "Bug", "Poison"),
    "Beedrill": Gen_1("Beedrill",  1.0, 29.5, "Kanto", "It has three poisonous stingers on its forelegs and its tail.  They are used to jab its enemy repeatedly.", "Bug", "Poison"),
    "Pidgey": Gen_1("Pidgey", 0.3, 1.8, "Kanto", "Very docile.  If attacked, it will often kick up sand to protect itself rather than fight back.", "Normal", "Flying"),
    "Pidgeotto": Gen_1("Pidgeotto", 1.1, 30.0, "Kanto", "This Pokémon is full of vitality.  It constantly flies around its large territory in search of prey.", "Normal", "Flying"),
    "Pidgeot": Gen_1("Pidgeot", 1.5, 39.5, "Kanto", "This Pokémon flies at Mack 2 speed, seeking prey.  Its large talons are feared as wicked weapons.", "Normal", "Flying"),
    "Rattata": Gen_1("Rattata", 0.3, 3.5, "Kanto", "Will chew on anything with its fangs.  If you see one, you can be certain that 40 more live in the area.", "Normal", None),
    "Raticate": Gen_1("Raticate", 0.7, 18.5, "Kanto","Its hind feet are webbed.  They act as flippers, so it can swim in rivers and hunt for prey.", "Normal", None),
    "Spearow": Gen_1("Spearow", 0.3, 2.0, "Kanto", "Inept at flying high, however, it can fly around very fast to protect its territory.", "Normal", "Flying"),
    "Fearow": Gen_1("Fearow", 1.2, 38.0, "Kanto", "A Pokémon that dates back many years.  If it senses danger, it flies high and away, instantly.", "Normal", "Flying"),
    "Ekans": Gen_1("Ekans", 2.0, 6.9, "Kanto", "The older it gets, the longer it grows.  At night it wraps its long body around tree branches to rest.", "Poison", None),
    "Arbok": Gen_1("Arbok", 3.5, 65.0, "Kanto", "The frightening patterns on its belly have been studied.  Six variations have been confirmed.", "Poison", None),
    "Pikachu": Gen_1("Pikachu", 0.4, 6.0, "Kanto", "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.", "Electric", None),
    "Raichu": Gen_1("Raichu", 0.8, 30.0, "Kanto", "Its long tail serves as a ground to protect itself from its own high-voltage power.", "Electric", None),
    "Sandshrew": Gen_1("Sandshrew", 0.6, 12.0, "Kanto", "It loves to bathe in teh grit of dry, sandy areas.  By sand bathing, the Pokémon rids itself of dirt and moisture clinging to its body.", "Ground", None),
    "Sandslash": Gen_1("Sandslash", 1.0, 29.5, "Kanto","The drier the area Sandslash lives in, the harder and smoother the Pokémon's spikes will feel when touched.", "Ground", None),
    "Nidoran (F)": Gen_1("Nidoran (F)", 0.4, 7.0, "Kanto", "Females are more sensitive to smells than males.  While foraging, they'll use their whiskers to check wind direction and stay downwind of predators.", "Poison", None),
    "Nidorina": Gen_1("Nidorina", 0.8, 20.0, "Kanto", "The horn in its head has atrophied.  Its thought that this happens so nidorina's children won't get poked while their mother is feeding them.", "Poison", None),
    "Nidoqueen": Gen_1("Nidoqueen", 1.3, 60.0, "Kanto", "Nidoqueen is better at defense than offense.  With scales like armor, this Pokémon will shield its children from any kind of attack.", "Poison", "Ground"),
    "Nidoran (M)": Gen_1("Nidoran (M)", 0.5, 9.0, "Kanto", "The horn on a male Nidoran's forehead contains a powerful poison.  This is a very cautious Pokémon, always straining its large ears.", "Poison", None),
    "Nidorino": Gen_1("Nidorino", 0.9, 19.5, "Kanto", "With a horn that's harder than diamond, this Pokémon goes around shattering boulders as it searches for a moon stone.", "Poison", None),
    "Nidoking": Gen_1("Nidoking" ,1.4, 62.0, "Kanto", "When it goes on a rampage, its impossible to control, but in the presence of Nidoqueen its lived with for a long time, Nidoking calms down.", "Poison", "Ground"),
    "Clefairy": Gen_1("Clefairy", 0.6, 7.5, "Kanto", "It is said that happiness will come to those who see a gathering of Clefairy dancing under a full moon.", "Fairy", None),
    "Clefable": Gen_1("Clefable", 1.3, 40.0, "Kanto", "A timid fairy Pokémon that is rarely seen, it will run and hide the moment it senses people.", "Fairy", None),
    "Vulpix": Gen_1("Vulpix", 0.6, 9.9, "Kanto", "While young, it has six gorgeous tails.  When it grows, several new tails are sprouted.", "Fire", None),
    "Ninetales": Gen_1("Ninetales", 1.1, 19.9, "Kanto", "It is said to live 1,000 years, and each of its tails is loaded with supernatural powers.", "Fire", None),
    "Jigglypuff": Gen_1("Jigglypuff", 0.5, 5.5, "Kanto", "Jigglypuff has top-notch lung capacity, even by comparison to other Pokémon.  It won't stop singing its lullabies until its foes fall asleep.", "Normal", "Fairy"),
    "Wigglytuff": Gen_1("Wigglytuff", 1.0, 12.0, "Kanto", "the more air it takes, in, the more it inflates.  If opponents catch it in a bad mood, it will inflate itself ot an enormous size to intimidate them.", "Normal", "Fairy"),
    "Zubat": Gen_1("Zubat", 0.8, 7.5, "Kanto", "It emits ultrasonic waves from its mouth to check its surroundings. Even in tight caves, Zubat flies around with skill.", "Poison", "Flying"),
    "Golbat": Gen_1("Golbat", 1.6, 55.0, "Kanto","It loves to drink other creatures’ blood. It’s said that if it finds others of its kind going hungry, it sometimes shares the blood it’s gathered.", "Poison", "Flying"),
    "Oddish": Gen_1("Oddish", 0.5, 5.4, "Kanto", "If exposed to moonlight, it starts to move. It roams far and wide at night to scatter its seeds.", "Grass", "Poison"),
    "Gloom": Gen_1("Gloom", 0.8, 8.6, "Kanto", "Its pistils exude an incredibly foul odor. The horrid stench can cause fainting at a distance of 1.25 miles.", "Grass", "Poison"),
    "Vileplume": Gen_1("Vileplume", 1.2, 18.6, "Kanto", "It has the world’s largest petals. With every step, the petals shake out heavy clouds of toxic pollen.", "Grass", "Poison"),
    "Paras": Gen_1("Paras", 0.3, 5.4, "Kanto", "Burrows under the ground to gnaw on tree roots. The mushrooms on its back absorb most of the nutrition.", "Bug", "Grass"),
    "Parasect": Gen_1("Parasect", 1.0, 29.5, "Kanto","The bug host is drained of energy by the mushroom on its back. The mushroom appears to do all the thinking.", "Bug", "Grass"),
    "Venonat": Gen_1("Venonat", 1.0, 30.0, "Kanto", "Its large eyes act as radar. In a bright place, you can see that they are clusters of many tiny eyes.", "Bug", "Poison"),
    "Venomoth": Gen_1("Venomoth", 1.5, 12.5, "Kanto", "The powdery scales on its wings are hard to remove from skin. They also contain poison that leaks out on contact.", "Bug", "Poison"),
    "Diglett": Gen_1("Diglett", 0.2, 0.8, "Kanto", "If a Diglett digs through a field, it leaves the soil perfectly tilled and ideal for planting crops.", "Ground", None),
    "Dugtrio": Gen_1("Dugtrio", 0.7, 66.6, "Kanto", "A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.", "Ground", None),
    "Meowth": Gen_1("Meowth", 0.4, 4.2, "Kanto", "It loves to collect shiny things. If it’s in a good mood, it might even let its Trainer have a look at its hoard of treasures.", "Normal", None),
    "Persian": Gen_1("Persian", 1.1, 33.0, "Kanto", "Getting this prideful Pokémon to warm up to you takes a lot of effort, and it will claw at you the moment it gets annoyed.", "Normal", None),
    "Psyduck": Gen_1("Psyduck", 0.8, 19.6, "Kanto", "Psyduck is constantly beset by headaches. If the Pokémon lets its strange power erupt, apparently the pain subsides for a while.", "Water", None),
    "Golduck": Gen_1("Golduck", 1.7, 76.6, "Kanto", "This Pokémon lives in gently flowing rivers. It paddles through the water with its long limbs, putting its graceful swimming skills on display.", "Water", None),
    "Mankey": Gen_1("Mankey", 0.5, 28.0, "Kanto", "An agile Pokémon that lives in trees. It angers easily and will not hesitate to attack anything.", "Fighting", None),
    "Primeape": Gen_1("Primeape", 1.0, 32.0, "Kanto", "It stops being angry only when nobody else is around. To view this moment is very difficult.", "Fighting", None),
    "Growlithe": Gen_1("Growlithe", 0.7, 19.0, "Kanto", "It has a brave and trustworthy nature. It fearlessly stands up to bigger and stronger foes.", "Fire", None),
    "Arcanine": Gen_1("Arcanine", 1.9, 155.0, "Kanto", "The sight of it running over 6,200 miles in a single day and night has captivated many people.", "Fire", None),
    "Poliwag": Gen_1("Poliwag", 0.6, 12.4, "Kanto", "For Poliwag, swimming is easier than walking. The swirl pattern on its belly is actually part of the Pokémon’s innards showing through the skin.", "Water", None),
    "Poliwhirl": Gen_1("Poliwhirl", 1.0, 20.0, "Kanto", "Staring at the swirl on its belly causes drowsiness. This trait of Poliwhirl’s has been used in place of lullabies to get children to go to sleep.", "Water", None),
    "Poliwrath": Gen_1("Poliwrath", 1.3, 54.0, "Kanto", "Its body is solid muscle. When swimming through cold seas, Poliwrath uses its impressive arms to smash through drift ice and plow forward.", "Water", "Fighting"),
    "Abra": Gen_1("Abra", 0.9, 19.5, "Kanto", "This Pokémon uses its psychic powers while it sleeps. The contents of Abra’s dreams affect the powers that the Pokémon wields.", "Psychic", None),
    "Kadabra": Gen_1("Kadabra", 1.3, 56.5, "Kanto", "Using its psychic power, Kadabra levitates as it sleeps. It uses its springy tail as a pillow.", "Psychic", None),
    "Alakazam": Gen_1("Alakazam", 1.5, 48.0, "Kanto", "It has an incredibly high level of intelligence. Some say that Alakazam remembers everything that ever happens to it, from birth till death.", "Psychic", None),
    "Machop": Gen_1("Machop", 0.8, 19.5, "Kanto", "Its whole body is composed of muscles. Even though it’s the size of a human child, it can hurl 100 grown-ups.", "Fighting", None),
    "Machoke": Gen_1("Machoke", 1.5, 70.5, "Kanto", "Its muscular body is so powerful, it must wear a power-save belt to be able to regulate its motions.", "Fighting", None),
    "Machamp": Gen_1("Machamp", 1.6, 130.0, "Kanto", "It quickly swings its four arms to rock its opponents with ceaseless punches and chops from all angles.", "Fighting", None),
    "Bellsprout": Gen_1("Bellsprout", 0.7, 4.0, "Kanto", "Prefers hot and humid places. It ensnares tiny bugs with its vines and devours them.", "Grass", "Poison"),
    "Weepinbell": Gen_1("Weepinbell", 1.0, 6.4, "Kanto", "When hungry, it swallows anything that moves. Its hapless prey is dissolved by strong acids.", "Grass", "Poison"),
    "Victreebel": Gen_1("Victreebel", 1.7, 15.5, "Kanto", "Lures prey with the sweet aroma of honey. Swallowed whole, the prey is dissolved in a day, bones and all.", "Grass", "Poison"),
    "Tentacool": Gen_1("Tentacool", 0.9, 45.5, "Kanto", "Tentacool is not a particularly strong swimmer. It drifts across the surface of shallow seas as it searches for prey.", "Water", "Poison"),
    "Tentacruel": Gen_1("Tentacruel", 1.6, 55.0, "Kanto", "When the red orbs on Tentacruel’s head glow brightly, watch out. The Pokémon is about to fire off a burst of ultrasonic waves.", "Water", "Poison"),
    "Geodude": Gen_1("Geodude", 0.4, 20.0, "Kanto", "Commonly found near mountain trails and the like. If you step on one by accident, it gets angry.", "Rock", "Ground"),
    "Graveler": Gen_1("Graveler", 1.0, 105.0, "Kanto", "Often seen rolling down mountain trails. Obstacles are just things to roll straight over, not avoid.", "Rock", "Ground"),
    "Golem": Gen_1("Golem", 1.7, 316.0, "Kanto", "Once it sheds its skin, its body turns tender and whitish. Its hide hardens when it’s exposed to air.","Rock", "Ground"),
    "Ponyta": Gen_1("Ponyta", 1.0, 30.0, "Kanto", "It can’t run properly when it’s newly born. As it races around with others of its kind, its legs grow stronger.", "Fire", None),
    "Rapidash": Gen_1("Rapidash", 1.7, 95.0, "Kanto", "This Pokémon can be seen galloping through fields at speeds of up to 150 mph, its fiery mane fluttering in the wind.", "Fire", None), 
    "Slowpoke": Gen_1("Slowpoke", 1.2, 36.0, "Kanto", "Slow-witted and oblivious, this Pokémon won’t feel any pain if its tail gets eaten. It won’t notice when its tail grows back, either.", "Water", "Psychic"),
    "Slowbro": Gen_1("Slowbro", 1.6, 78.5, "Kanto", "Slowpoke became Slowbro when a Shellder bit on to its tail. Sweet flavors seeping from the tail make the Shellder feel as if its life is a dream.", "Water", "Psychic"),
    "Magnemite": Gen_1("Magnemite", 0.3, 6.0, "Kanto","At times, Magnemite runs out of electricity and ends up on the ground. If you give batteries to a grounded Magnemite, it’ll start moving again.", "Electric", "Steel"),
    "Magneton": Gen_1("Magneton", 1.0, 60.0, "Kanto", "This Pokémon is three Magnemite that have linked together. Magneton sends out powerful radio waves to study its surroundings.", "Electric", "Steel"),
    "Farfetch'd": Gen_1("Farfetch'd", 0.8, 42.0, "Kanto", "The stalk this Pokémon carries in its wings serves as a sword to cut down opponents. In a dire situation, the stalk can also serve as food.", "Normal", "Flying"),
    "Doduo": Gen_1("Doduo", 1.4, 39.2, "Kanto", "Its short wings make flying difficult. Instead, this Pokémon runs at high speed on developed legs.", "Normal", "Flying"),
    "Dodrio": Gen_1("Dodrio", 1.8, 85.2, "Kanto", "One of Doduo’s two heads splits to form a unique species. It runs close to 40 mph in prairies.", "Normal", "Flying"),
    "Seel": Gen_1("Seel", 1.1, 90.0, "Kanto", "Loves freezing-cold conditions. Relishes swimming in a frigid climate of around 14 degrees Fahrenheit.","Water", None),
    "Dewgong": Gen_1("Dewgong", 1.7, 120.0, "Kanto", "Its entire body is a snowy white. Unharmed by even intense cold, it swims powerfully in icy waters.", "Water", "Ice"),
    "Grimer": Gen_1("Grimer", 0.9, 30.0, "Kanto", "Made of congealed sludge. It smells too putrid to touch. Even weeds won’t grow in its path.", "Poison", None),
    "Muk": Gen_1("Muk", 1.2, 30.0, "Kanto", "Smells so awful, it can cause fainting. Through degeneration of its nose, it lost its sense of smell.", "Poison", None),
    "Shellder": Gen_1("Shellder", 0.3, 4.0, "Kanto", "It swims facing backward by opening and closing its two-piece shell. It is surprisingly fast.", "Water", None),
    "Cloyster": Gen_1("Cloyster", 1.5, 132.5, "Kanto", "Its shell is extremely hard. It cannot be shattered, even with a bomb. The shell opens only when it is attacking.", "Water", "Ice"),
    "Gastly": Gen_1("Gastly", 1.3, 0.1, "Kanto", "Born from gases, anyone would faint if engulfed by its gaseous body, which contains poison.", "Ghost", "Poison"),
    "Haunter": Gen_1("Haunter", 1.6, 0.1, "Kanto", "Its tongue is made of gas. If licked, its victim starts shaking constantly until death eventually comes.", "Ghost", "Poison"),
    "Gengar": Gen_1("Gengar", 1.5, 40.5, "Kanto", "On the night of a full moon, if shadows move on their own and laugh, it must be Gengar’s doing.", "Ghost", "Poison"),
    "Onix": Gen_1("Onix", 8.8, 210.0, "Kanto", "As it digs through the ground, it absorbs many hard objects. This is what makes its body so solid.", "Rock", "Ground"),
    "Drowzee": Gen_1("Drowzee", 1.0, 32.4, "Kanto", "If you sleep by it all the time, it will sometimes show you dreams it had eaten in the past.","Psychic", None),
    "Hypno": Gen_1("Hypno", 1.6, 75.6, "Kanto", "Avoid eye contact if you come across one. It will try to put you to sleep by using its pendulum.", "Psychic", None),
    "Krabby": Gen_1("Krabby", 0.4, 6.5, "Kanto", "It can be found near the sea. The large pincers grow back if they are torn out of their sockets.", "Water", None),
    "Kingler": Gen_1("Kingler", 1.3, 60.0, "Kanto", "Its large and hard pincer has 10,000-horsepower strength. However, being so big, it is unwieldy to move.", "Water", None),
    "Voltorb": Gen_1("Voltorb", 0.5, 10.4, "Kanto", "It is said to camouflage itself as a Poké Ball. It will self-destruct with very little stimulus.", "Electric", None),
    "Electrode": Gen_1("Electrode", 1.2, 66.6, "Kanto", "Stores electrical energy inside its body. Even the slightest shock could trigger a huge explosion.", "Electric", None),
    "Exeggcute": Gen_1("Exeggcute", 0.4, 2.5, "Kanto", "Though it may look like it’s just a bunch of eggs, it’s a proper Pokémon. Exeggcute communicates with others of its kind via telepathy, apparently.", "Grass", "Psychic"),
    "Exeggutor": Gen_1("Exeggutor", 2.0, 120.0, "Kanto", "Each of Exeggutor’s three heads is thinking different thoughts. The three don’t seem to be very interested in one another.", "Grass", "Psychic"),
    "Cubone": Gen_1("Cubone", 0.4, 6.5, "Kanto", "When the memory of its departed mother brings it to tears, its cries echo mournfully within the skull it wears on its head.", "Ground", None),
    "Marowak": Gen_1("Marowak", 1.0, 45.0, "Kanto", "This Pokémon overcame its sorrow to evolve a sturdy new body. Marowak faces its opponents bravely, using a bone as a weapon.", "Ground", None),
    "Hitmonlee": Gen_1("Hitmonlee", 1.5, 49.8, "Kanto", "This amazing Pokémon has an awesome sense of balance. It can kick in succession from any position.", "Fighting", None),
    "Hitmonchan": Gen_1("Hitmonchan", 1.4, 50.2, "Kanto", "Its punches slice the air. They are launched at such high speed, even a slight graze could cause a burn.", "Fighting", None),
    "Lickitung": Gen_1("Lickitung", 1.2, 65.5, "Kanto", "If this Pokémon’s sticky saliva gets on you and you don’t clean it off, an intense itch will set in. The itch won’t go away, either.", "Normal", None),
    "Koffing": Gen_1("Koffing", 0.6, 1.0, "Kanto", "Its body is full of poisonous gas. It floats into garbage dumps, seeking out the fumes of raw, rotting trash.", "Poison", None),
    "Weezing": Gen_1("Weezing", 1.2, 9.5, "Kanto", "It mixes gases between its two bodies. It’s said that these Pokémon were seen all over the Galar region back in the day.", "Poison", None),
    "Rhyhorn": Gen_1("Rhyhorn", 1.0, 115.0, "Kanto", "Strong, but not too bright, this Pokémon can shatter even a skyscraper with its charging tackles.", "Ground", "Rock"),
    "Rhydon": Gen_1("Rhydon", 1.9, 120.0, "Kanto", "It begins walking on its hind legs after evolution. It can punch holes through boulders with its horn.", "Ground", "Rock"),
    "Chansey": Gen_1("Chansey", 1.1, 34.6, "Kanto", "The egg Chansey carries is not only delicious but also packed with nutrition. It’s used as a high-class cooking ingredient.", "Normal", None),
    "Tangela": Gen_1("Tangela", 1.0, 35.0, "Kanto", "Hidden beneath a tangle of vines that grows nonstop even if the vines are torn off, this Pokémon’s true appearance remains a mystery.", "Grass", None),
    "Kangaskhan": Gen_1("Kangaskhan", 2.2, 80.0, "Kanto", "Although it’s carrying its baby in a pouch on its belly, Kangaskhan is swift on its feet. It intimidates its opponents with quick jabs.", "Normal", None),
    "Horsea": Gen_1("Horsea", 0.4, 8.0, "Kanto", "Horsea makes its home in oceans with gentle currents. If this Pokémon is under attack, it spits out pitch-black ink and escapes.", "Water", None),
    "Seadra": Gen_1("Seadra", 1.2, 25.0, "Kanto", "It’s the males that raise the offspring. While Seadra are raising young, the spines on their backs secrete thicker and stronger poison.", "Water", None),
    "Goldeen": Gen_1("Goldeen", 0.6, 15.0, "Kanto", "Its dorsal, pectoral, and tail fins wave elegantly in water. That is why it is known as the Water Dancer.", "Water", None),
    "Seaking": Gen_1("Seaking", 1.3, 39.0, "Kanto", "In autumn, its body becomes more fatty in preparing to propose to a mate. It takes on beautiful colors.", "Water", None),
    "Staryu": Gen_1("Staryu", 0.8, 34.5, "Kanto", "If you visit a beach at the end of summer, you’ll be able to see groups of Staryu lighting up in a steady rhythm.", "Water", None),
    "Starmie": Gen_1("Starmie", 1.1, 80.0, "Kanto", "This Pokémon has an organ known as its core. The organ glows in seven colors when Starmie is unleashing its potent psychic powers.", "Water", "Psychic"),
    "Mr. Mime": Gen_1("Mr. Mime", 1.3, 54.5, "Kanto", "The broadness of its hands may be no coincidence—many scientists believe its palms became enlarged specifically for pantomiming.", "Psychic", "Fairy"),
    "Scyther": Gen_1("Scyther", 1.5, 56.0, "Kanto", "As Scyther fights more and more battles, its scythes become sharper and sharper. With a single slice, Scyther can fell a massive tree.", "Bug", "Flying"),
    "Jynx": Gen_1("Jynx", 1.4, 40.6, "Kanto", "In certain parts of Galar, Jynx was once feared and worshiped as the Queen of Ice.", "Ice", "Psychic"),
    "Electabuzz": Gen_1("Electabuzz", 1.1, 30.0, "Kanto", "Many power plants keep Ground-type Pokémon around as a defense against Electabuzz that come seeking electricity.", "Electric", None),
    "Magmar": Gen_1("Magmar", 1.3, 44.5, "Kanto", "Magmar dispatches its prey with fire. But it regrets this habit once it realizes that it has burned its intended prey to a charred crisp.", "Fire", None),
    "Pinsir": Gen_1("Pinsir", 1.5, 55.0, "Kanto", "These Pokémon judge one another based on pincers. Thicker, more impressive pincers make for more popularity with the opposite gender.", "Bug", None),
    "Tauros": Gen_1("Tauros", 1.4, 88.4, "Kanto", "When Tauros begins whipping itself with its tails, it’s a warning that the Pokémon is about to charge with astounding speed.", "Normal", None),
    "Magikarp": Gen_1("Magikarp", 0.9, 10.0, "Kanto", "It is virtually worthless in terms of both power and speed. It is the most weak and pathetic Pokémon in the world.", "Water", None),
    "Gyarados": Gen_1("Gyarados", 6.5, 235.0, "Kanto", "It has an extremely aggressive nature. The Hyper Beam it shoots from its mouth totally incinerates all targets.", "Water", "Flying"),
    "Lapras": Gen_1("Lapras", 2.5, 220.0, "Kanto", "A smart and kindhearted Pokémon, it glides across the surface of the sea while its beautiful song echoes around it.", "Water", "Ice"),
    "Ditto": Gen_1("Ditto", 0.3, 4.0, "Kanto", "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.", "Normal", None),
    "Eevee": Gen_1("Eevee", 0.3, 6.5, "Kanto", "It has the ability to alter the composition of its body to suit its surrounding environment.", "Normal", None),
    "Vaporeon": Gen_1("Vaporeon", 1.0, 29.0, "Kanto", "When Vaporeon’s fins begin to vibrate, it is a sign that rain will come within a few hours.", "Water", None),
    "Jolteon": Gen_1("Jolteon", 0.8, 24.5, "Kanto", "If it is angered or startled, the fur all over its body bristles like sharp needles that pierce foes.", "Electric", None),
    "Flareon": Gen_1("Flareon", 0.9, 25.0, "Kanto", "Once it has stored up enough heat, this Pokémon’s body temperature can reach up to 1,700 degrees Fahrenheit.", "Fire", None),
    "Porygon": Gen_1("Porygon", 0.8, 36.5, "Kanto", "State-of-the-art technology was used to create Porygon. It was the first artificial Pokémon to be created via computer programming.", "Normal", None),
    "Omanyte": Gen_1("Omanyte", 0.4, 7.5, "Kanto", "Because some Omanyte manage to escape after being restored or are released into the wild by people, this species is becoming a problem.", "Rock", "Water"),
    "Omastar": Gen_1("Omastar", 1.0, 35.0, "Kanto", "Weighed down by a large and heavy shell, Omastar couldn’t move very fast. Some say it went extinct because it was unable to catch food.", "Rock", "Water"),
    "Kabuto": Gen_1("Kabuto", 0.5, 11.5, "Kanto", "This species is almost entirely extinct. Kabuto molt every three days, making their shells harder and harder.", "Rock", "Water"),
    "Kabutops": Gen_1("Kabutops", 1.3, 40.5, "Kanto", "Kabutops slices its prey apart and sucks out the fluids. The discarded body parts become food for other Pokémon.", "Rock", "Water"),
    "Aerodactyl": Gen_1("Aerodactyl", 1.8, 59.0, "Kanto", "This is a ferocious Pokémon from ancient times. Apparently even modern technology is incapable of producing a perfectly restored specimen.", "Rock", "Flying"),
    "Snorlax": Gen_1("Snorlax", 2.1, 460.0, "Kanto", "It is not satisfied unless it eats over 880 pounds of food every day. When it is done eating, it goes promptly to sleep.", "Normal", None),
    "Articuno": Gen_1("Aricuno", 1.7, 55.4, "Kanto", "It’s said that this Pokémon’s beautiful blue wings are made of ice. Articuno flies over snowy mountains, its long tail fluttering along behind it.", "Ice", "Flying"),
    "Zapdos": Gen_1("Zapdos", 1.6, 52.6, "Kanto", "This Pokémon has complete control over electricity. There are tales of Zapdos nesting in the dark depths of pitch-black thunderclouds.", "Electric", "Flying"),
    "Moltres": Gen_1("Moltres", 2.0, 60.0, "Kanto", "It’s one of the legendary bird Pokémon. When Moltres flaps its flaming wings, they glimmer with a dazzling red glow.", "Fire", "Flying"),
    "Dratini": Gen_1("Dratini", 1.8, 3.3, "Kanto", "Dratini dwells near bodies of rapidly flowing water, such as the plunge pools of waterfalls. As it grows, Dratini will shed its skin many times.", "Dragon", None),
    "Dragonair": Gen_1("Dragonair", 4.0, 16.5, "Kanto", "This Pokémon lives in pristine oceans and lakes. It can control the weather, and it uses this power to fly into the sky, riding on the wind.", "Dragon", None),
    "Dragonite": Gen_1("Dragonite", 2.2, 210.0, "Kanto", "It’s a kindhearted Pokémon. If it spots a drowning person or Pokémon, Dragonite simply must help them.", "Dragon", "Flying"),
    "Mewtwo": Gen_1("Mewtwo", 2.0, 122.0, "Kanto", "Its DNA is almost the same as Mew’s. However, its size and disposition are vastly different.", "Psychic", None),
    "Mew": Gen_1("Mew", 0.4, 4.0, "Kanto", "When viewed through a microscope, this Pokémon’s short, fine, delicate hair can be seen.", "Psychic", None)
} 

Pokemon_links = {
    "Bulbasaur": "https://cdn2.bulbagarden.net/upload/thumb/2/21/001Bulbasaur.png/250px-001Bulbasaur.png",
    "Ivysaur": "https://cdn2.bulbagarden.net/upload/thumb/7/73/002Ivysaur.png/250px-002Ivysaur.png",
    "Venusaur": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png",
    "Charmander": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png",
    "Charmeleon": "https://static.pokemonpets.com/images/monsters-images-300-300/5-Charmeleon.webp",
    "Charizard": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png",
    "Squirtle": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png",
    "Wartortle": "https://static.pokemonpets.com/images/monsters-images-800-800/8-Wartortle.webp",
    "Blastoise": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png",
    "Caterpie": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png",
    "Metapod": "https://static.pokemonpets.com/images/monsters-images-800-800/11-Metapod.webp",
    "Butterfree": "https://cdn2.bulbagarden.net/upload/thumb/d/d1/012Butterfree.png/1200px-012Butterfree.png",
    "Weedle": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png",
    "Kakuna": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png",
    "Beedrill": "https://static.pokemonpets.com/images/monsters-images-800-800/15-Beedrill.webp",
    "Pidgey": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png",
    "Pidgeotto": "https://cdn2.bulbagarden.net/upload/thumb/7/7a/017Pidgeotto.png/250px-017Pidgeotto.png",
    "Pidgeot": "https://static.wikia.nocookie.net/pokemon-encyclopedia/images/5/57/018Pidgeot.png/revision/latest/scale-to-width-down/250?cb=20171201160726",
    "Rattata": "https://cdn2.bulbagarden.net/upload/thumb/4/46/019Rattata.png/250px-019Rattata.png",
    "Raticate": "https://cdn2.bulbagarden.net/upload/thumb/f/f4/020Raticate.png/250px-020Raticate.png",
    "Spearow": "https://static.pokemonpets.com/images/monsters-images-800-800/21-Spearow.webp",
    "Fearow": "https://static.wikia.nocookie.net/project-pokemon/images/4/41/Fearow.png/revision/latest/top-crop/width/360/height/450?cb=20170511161826",
    "Ekans": "https://cdn2.bulbagarden.net/upload/f/fa/023Ekans.png",
    "Arbok": "https://cdn2.bulbagarden.net/upload/c/cd/024Arbok.png",
    "Pikachu": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png",
    "Raichu": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png",
    "Sandshrew": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/027.png",
    "Sandslash": "https://pokestop.io/img/pokemon/sandslash-256x256.png",
    "Nidoran (F)": "https://cdn2.bulbagarden.net/upload/8/81/029Nidoran.png",
    "Nidorina": "https://cdn2.bulbagarden.net/upload/c/cd/030Nidorina.png",
    "Nidoqueen": "https://cdn2.bulbagarden.net/upload/thumb/b/bf/031Nidoqueen.png/250px-031Nidoqueen.png",
    "Nidoran (M)": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/032.png",
    "Nidorino": "https://cdn2.bulbagarden.net/upload/9/9f/033Nidorino.png",
    "Nidoking": "https://cdn2.bulbagarden.net/upload/thumb/c/c6/034Nidoking.png/250px-034Nidoking.png",
    "Clefairy": "https://cdn2.bulbagarden.net/upload/thumb/f/f4/035Clefairy.png/250px-035Clefairy.png",
    "Clefable": "https://cdn2.bulbagarden.net/upload/thumb/a/a9/036Clefable.png/250px-036Clefable.png",
    "Vulpix": "https://cdn2.bulbagarden.net/upload/thumb/6/60/037Vulpix.png/1200px-037Vulpix.png",
    "Ninetales": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/038.png",
    "Jigglypuff": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/039.png",
    "Wigglytuff": "https://cdn2.bulbagarden.net/upload/thumb/9/92/040Wigglytuff.png/250px-040Wigglytuff.png",
    "Zubat": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/041.png",
    "Golbat": "https://cdn2.bulbagarden.net/upload/0/0c/042Golbat.png",
    "Oddish": "https://static.pokemonpets.com/images/monsters-images-800-800/43-Oddish.webp",
    "Gloom": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/044.png",
    "Vileplume": "https://static.pokemonpets.com/images/monsters-images-800-800/45-Vileplume.webp",
    "Paras": "https://cdn2.bulbagarden.net/upload/d/d4/046Paras.png",
    "Parasect": "https://cdn2.bulbagarden.net/upload/8/80/047Parasect.png",
    "Venonat": "https://images.gameinfo.io/pokemon/256/p48f217.png",
    "Venomoth": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/049.png",
    "Diglett": "https://cdn2.bulbagarden.net/upload/thumb/3/31/050Diglett.png/250px-050Diglett.png",
    "Dugtrio": "https://cdn2.bulbagarden.net/upload/thumb/e/e5/051Dugtrio.png/250px-051Dugtrio.png",
    "Meowth": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/052.png",
    "Persian": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/053.png",
    "Psyduck": "https://cdn2.bulbagarden.net/upload/thumb/5/53/054Psyduck.png/1200px-054Psyduck.png",
    "Golduck": "https://cdn2.bulbagarden.net/upload/thumb/f/fe/055Golduck.png/250px-055Golduck.png",
    "Mankey": "https://cdn2.bulbagarden.net/upload/4/41/056Mankey.png",
    "Primeape": "https://cdn2.bulbagarden.net/upload/9/9a/057Primeape.png",
    "Growlithe": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/058.png",
    "Arcanine": "https://static.wikia.nocookie.net/sonicpokemon/images/0/01/Arcanine_AG_anime.png/revision/latest/scale-to-width-down/2000?cb=20210118185852",
    "Poliwag": "https://cdn2.bulbagarden.net/upload/thumb/4/49/060Poliwag.png/250px-060Poliwag.png",
    "Poliwhirl": "https://cdn2.bulbagarden.net/upload/a/a9/061Poliwhirl.png",
    "Poliwrath": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/062.png",
    "Abra": "https://static.pokemonpets.com/images/monsters-images-800-800/63-Abra.webp",
    "Kadabra": "https://cdn2.bulbagarden.net/upload/9/97/064Kadabra.png",
    "Alakazam": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/065.png",
    "Machop": "https://gamepress.gg/pokemonmasters/sites/pokemonmasters/files/2020-09/pm0066_00_wanriky_256.ktx__2.png",
    "Machoke": "https://static.pokemonpets.com/images/monsters-images-800-800/67-Machoke.webp",
    "Machamp": "https://cdn2.bulbagarden.net/upload/thumb/8/8f/068Machamp.png/250px-068Machamp.png",
    "Bellsprout": "https://cdn2.bulbagarden.net/upload/thumb/a/a2/069Bellsprout.png/250px-069Bellsprout.png",
    "Weepinbell": "https://cdn2.bulbagarden.net/upload/9/9f/070Weepinbell.png",
    "Victreebel": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/071.png",
    "Tentacool": "https://static.pokemonpets.com/images/monsters-images-800-800/72-Tentacool.webp",
    "Tentacruel": "https://static.pokemonpets.com/images/monsters-images-800-800/73-Tentacruel.webp",
    "Geodude": "https://cdn2.bulbagarden.net/upload/thumb/9/98/074Geodude.png/250px-074Geodude.png",
    "Graveler": "https://cdn2.bulbagarden.net/upload/thumb/7/75/075Graveler.png/250px-075Graveler.png",
    "Golem": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/076.png",
    "Ponyta": "https://cdn2.bulbagarden.net/upload/thumb/3/3b/077Ponyta.png/250px-077Ponyta.png",
    "Rapidash": "https://cdn2.bulbagarden.net/upload/3/3f/078Rapidash.png",
    "Slowpoke": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/079.png",
    "Slowbro": "https://cdn2.bulbagarden.net/upload/thumb/8/80/080Slowbro.png/250px-080Slowbro.png",
    "Magnemite": "https://cdn2.bulbagarden.net/upload/thumb/6/6c/081Magnemite.png/250px-081Magnemite.png",
    "Magneton": "https://cdn2.bulbagarden.net/upload/thumb/7/72/082Magneton.png/250px-082Magneton.png",
    "Farfetch'd": "https://cdn2.bulbagarden.net/upload/thumb/f/f8/083Farfetch%27d.png/250px-083Farfetch%27d.png",
    "Doduo": "https://cdn2.bulbagarden.net/upload/thumb/5/54/084Doduo.png/250px-084Doduo.png",
    "Dodrio": "https://cdn2.bulbagarden.net/upload/9/93/085Dodrio.png",
    "Seel": "https://cdn2.bulbagarden.net/upload/thumb/1/1f/086Seel.png/250px-086Seel.png",
    "Dewgong": "https://cdn2.bulbagarden.net/upload/thumb/c/c7/087Dewgong.png/250px-087Dewgong.png",
    "Grimer": "https://cdn2.bulbagarden.net/upload/thumb/a/a0/088Grimer.png/250px-088Grimer.png",
    "Muk": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/089.png",
    "Shellder": "https://cdn2.bulbagarden.net/upload/4/40/090Shellder.png",
    "Cloyster": "https://static.pokemonpets.com/images/monsters-images-800-800/91-Cloyster.webp",
    "Gastly": "https://cdn2.bulbagarden.net/upload/thumb/c/ca/092Gastly.png/250px-092Gastly.png",
    "Haunter": "https://cdn2.bulbagarden.net/upload/thumb/6/62/093Haunter.png/250px-093Haunter.png",
    "Gengar": "https://cdn2.bulbagarden.net/upload/thumb/c/c6/094Gengar.png/250px-094Gengar.png",
    "Onix": "https://cdn2.bulbagarden.net/upload/thumb/9/9a/095Onix.png/1200px-095Onix.png",
    "Drowzee": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/096.png",
    "Hypno": "https://cdn2.bulbagarden.net/upload/thumb/0/0a/097Hypno.png/250px-097Hypno.png",
    "Krabby": "https://cdn2.bulbagarden.net/upload/a/a7/098Krabby.png",
    "Kingler": "https://cdn2.bulbagarden.net/upload/7/71/099Kingler.png",
    "Voltorb": "https://cdn2.bulbagarden.net/upload/thumb/d/da/100Voltorb.png/250px-100Voltorb.png",
    "Electrode": "https://cdn2.bulbagarden.net/upload/thumb/8/84/101Electrode.png/250px-101Electrode.png",
    "Exeggcute": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/102.png",
    "Exeggutor": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/103.png",
    "Cubone": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/104.png",
    "Marowak": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/105.png",
    "Hitmonlee": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/106.png",
    "Hitmonchan": "https://cdn2.bulbagarden.net/upload/a/a3/107Hitmonchan.png",
    "Lickitung": "https://static.pokemonpets.com/images/monsters-images-800-800/108-Lickitung.webp",
    "Koffing": "https://cdn2.bulbagarden.net/upload/1/17/109Koffing.png",
    "Weezing": "https://static.pokemonpets.com/images/monsters-images-800-800/110-Weezing.webp",
    "Rhyhorn": "https://static.pokemonpets.com/images/monsters-images-800-800/111-Rhyhorn.webp",
    "Rhydon": "https://static.pokemonpets.com/images/monsters-images-800-800/112-Rhydon.webp",
    "Chansey": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/113.png",
    "Tangela": "https://cdn2.bulbagarden.net/upload/3/3e/114Tangela.png",
    "Kangaskhan": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/115.png",
    "Horsea": "https://static.pokemonpets.com/images/monsters-images-800-800/116-Horsea.webp",
    "Seadra": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/117.png",
    "Goldeen": "https://cdn2.bulbagarden.net/upload/7/7b/118Goldeen.png",
    "Seaking": "https://cdn2.bulbagarden.net/upload/6/6a/119Seaking.png",
    "Staryu": "https://cdn2.bulbagarden.net/upload/4/4f/120Staryu.png",
    "Starmie": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/121.png",
    "Mr. Mime": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/122.png",
    "Scyther": "https://cdn2.bulbagarden.net/upload/b/ba/123Scyther.png",
    "Jynx": "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/3321c70e-a1a8-4754-9c16-dde2c745e9c4/d2eoeru-236e9cc5-3346-4138-ad6b-8bf3c7fd8165.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzMzMjFjNzBlLWExYTgtNDc1NC05YzE2LWRkZTJjNzQ1ZTljNFwvZDJlb2VydS0yMzZlOWNjNS0zMzQ2LTQxMzgtYWQ2Yi04YmYzYzdmZDgxNjUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.h60Psx2ERdH4VjYCwPb9dL06b3pHAAEsjICWK1or_IU",
    "Electabuzz": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/125.png",
    "Magmar": "https://cdn2.bulbagarden.net/upload/thumb/8/8c/126Magmar.png/1200px-126Magmar.png",
    "Pinsir": "https://cdn2.bulbagarden.net/upload/thumb/7/71/127Pinsir.png/1200px-127Pinsir.png",
    "Tauros": "https://cdn2.bulbagarden.net/upload/thumb/b/b8/128Tauros.png/250px-128Tauros.png",
    "Magikarp": "https://cdn2.bulbagarden.net/upload/thumb/0/02/129Magikarp.png/250px-129Magikarp.png",
    "Gyarados": "https://cdn2.bulbagarden.net/upload/thumb/4/41/130Gyarados.png/250px-130Gyarados.png",
    "Lapras": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/131.png",
    "Ditto": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/132.png",
    "Eevee": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/133.png",
    "Vaporeon": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/134.png",
    "Jolteon": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/135.png",
    "Flareon": "https://cdn2.bulbagarden.net/upload/thumb/d/dd/136Flareon.png/250px-136Flareon.png",
    "Porygon": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/137.png",
    "Omanyte": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/138.png",
    "Omastar": "https://cdn2.bulbagarden.net/upload/4/43/139Omastar.png",
    "Kabuto": "https://cdn2.bulbagarden.net/upload/f/f9/140Kabuto.png",
    "Kabutops": "https://static.wikia.nocookie.net/pokemonordhon/images/5/5a/141-Kabutops.png/revision/latest?cb=20191106025214",
    "Aerodactyl": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/142.png",
    "Snorlax": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/143.png", 
    "Articuno": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/144.png",
    "Zapdos": "https://cdn2.bulbagarden.net/upload/thumb/e/e3/145Zapdos.png/250px-145Zapdos.png",
    "Moltres": "https://cdn2.bulbagarden.net/upload/thumb/1/1b/146Moltres.png/1200px-146Moltres.png",
    "Dratini": "https://cdn2.bulbagarden.net/upload/thumb/c/cc/147Dratini.png/250px-147Dratini.png",
    "Dragonair": "https://i.pinimg.com/originals/ac/ca/a1/accaa1ec7d2ea4160afea3a44592e188.png",
    "Dragonite": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png",
    "Mewtwo": "https://assets.pokemon.com/assets/cms2/img/pokedex/full/150.png",
    "Mew": "https://cdn2.bulbagarden.net/upload/thumb/b/b1/151Mew.png/250px-151Mew.png"
}
